// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using MauiApp1.mode;
//
//    var user = User.FromJson(jsonString);

namespace MauiApp1.model
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class User
    {
        [JsonProperty("studentId")]
        public string StudentId { get; set; }

        [JsonProperty("email")]
        public string Email { get; set; }

        [JsonProperty("password")]
        public string Password { get; set; }

        [JsonProperty("firstName")]
        public string FirstName { get; set; }

        [JsonProperty("lastName")]
        public string LastName { get; set; }

        [JsonProperty("profilePicture")]
        public string ProfilePicture { get; set; }

        [JsonProperty("year")]
        public long Year { get; set; }

        [JsonProperty("major")]
        public string Major { get; set; }

        [JsonProperty("currentSemesterCourses")]
        public List<CurrentSemesterCourse> CurrentSemesterCourses { get; set; }

        [JsonProperty("previousSemesterCourses")]
        public List<PreviousSemesterCourse> PreviousSemesterCourses { get; set; }
    }

    public partial class CurrentSemesterCourse
    {
        [JsonProperty("courseId")]
        public string CourseId { get; set; }

        [JsonProperty("courseName")]
        public string CourseName { get; set; }

        [JsonProperty("grade")]
        public object Grade { get; set; }
    }

    public partial class PreviousSemesterCourse
    {
        [JsonProperty("semester")]
        public string Semester { get; set; }

        [JsonProperty("courses")]
        public List<Course> Courses { get; set; }
    }

    public partial class Course
    {
        [JsonProperty("courseId")]
        public string CourseId { get; set; }

        [JsonProperty("courseName")]
        public string CourseName { get; set; }

        [JsonProperty("grade")]
        public string Grade { get; set; }
    }

    public partial class User
    {
        public static List<User> FromJson(string json) => JsonConvert.DeserializeObject<List<User>>(json, MauiApp1.model.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this List<User> self) => JsonConvert.SerializeObject(self, MauiApp1.model.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
